### ISSUE TITLE
Error loading plugin after upgrade to 0.1.7

### ISSUE THREAD

**Issue by ToddGreenfield** [dustindclark/homebridge-envisalink#16]
I just upgraded to 1.7 and get the following errors. I also tried to uninstall and reinstall with the same result. I also confirmed that nodealarmproxy is getting installed with 1.0.0 (from package.json in that dir).

May  6 10:26:00 homepi-a homebridge[1138]: [5/6/2017, 10:26:00 AM] ====================
May  6 10:26:00 homepi-a homebridge[1138]: [5/6/2017, 10:26:00 AM] ERROR LOADING PLUGIN homebridge-envisalink:
May  6 10:26:00 homepi-a homebridge[1138]: [5/6/2017, 10:26:00 AM] Error: Cannot find module 'nodealarmproxy/index.js'
May  6 10:26:00 homepi-a homebridge[1138]: at Function.Module._resolveFilename (module.js:469:15)
May  6 10:26:00 homepi-a homebridge[1138]: at Function.Module._load (module.js:417:25)
May  6 10:26:00 homepi-a homebridge[1138]: at Module.require (module.js:497:17)
May  6 10:26:00 homepi-a homebridge[1138]: at require (internal/module.js:20:19)
May  6 10:26:00 homepi-a homebridge[1138]: at Object.<anonymous> (/home/pi/.npm-global/lib/node_modules/homebridge-envisalink/index.js:2:11)
May  6 10:26:00 homepi-a homebridge[1138]: at Module._compile (module.js:570:32)
May  6 10:26:00 homepi-a homebridge[1138]: at Object.Module._extensions..js (module.js:579:10)
May  6 10:26:00 homepi-a homebridge[1138]: at Module.load (module.js:487:32)
May  6 10:26:00 homepi-a homebridge[1138]: at tryModuleLoad (module.js:446:12)
May  6 10:26:00 homepi-a homebridge[1138]: at Function.Module._load (module.js:438:3)
May  6 10:26:00 homepi-a homebridge[1138]: [5/6/2017, 10:26:00 AM] ====================

When I downgrade to 0.1.6 all works fine again.

**Comment by techminh** [comment]
I am having the same issue, getting errors loading plugin from envisalink and chamberlain plugins.

Todd, how did you downgrade?

**Comment by ToddGreenfield** [comment]
uninstall and then reinstall with
npm install -g homebridge-envisalink@0.1.6

**Comment by IMNotMax** [comment]
The downgrade works !

**Comment by IMNotMax** [comment]
Here my log if it helps

```
[2017-05-07 21:03:04] ====================
[2017-05-07 21:03:04] ERROR LOADING PLUGIN homebridge-envisalink:
[2017-05-07 21:03:04] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-envisalink/index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
[2017-05-07 21:03:04] ====================
```

**Comment by IMNotMax** [comment]
Still not working...


See the log with a fresh install on a raspberry pi 3

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-10-13 22:26:31] ====================
[2017-10-13 22:26:32] ERROR LOADING PLUGIN homebridge-envisalink:
[2017-10-13 22:26:32] Error: Cannot find module 'nodealarmproxy/index.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink/index.js:2:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
[2017-10-13 22:26:32] ====================
[2017-10-13 22:26:33] Loaded plugin: homebridge-platform-wemo
[2017-10-13 22:26:33] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2017-10-13 22:26:33] ---
[2017-10-13 22:26:34] Loaded plugin: homebridge-samsungtv2016
[2017-10-13 22:26:34] Registering accessory 'homebridge-samsungtv.SamsungTV2016'
[2017-10-13 22:26:34] ---
[2017-10-13 22:26:34] Loaded plugin: homebridge-ssh
[2017-10-13 22:26:34] Registering accessory 'homebridge-ssh.SSH'
[2017-10-13 22:26:34] ---
[2017-10-13 22:26:34] Loaded config.json with 3 accessories and 2 platforms.
[2017-10-13 22:26:34] ---
[2017-10-13 22:26:34] Loading 2 platforms...
[2017-10-13 22:26:34] [WeMo Platform] Initializing BelkinWeMo platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Envisalink' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by IMNotMax** [comment]
I need to stay on the 0.1.6 version
